version: '3.7'
services:
  app:
    image: maccpr7/sfia1:latest
    build: ./
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
  mysql-container:
    image: maccpr7/spring-db:latest
    build: ./mysql
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp

    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
